SELECT CADENA, CENTRO, CADENA_2, NOMBRE, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO,
       ENE_CANTIDAD,FEB_CANTIDAD,MAR_CANTIDAD,ABR_CANTIDAD,MAY_CANTIDAD,JUN_CANTIDAD,JUL_CANTIDAD,AGO_CANTIDAD,SET_CANTIDAD,OCT_CANTIDAD,NOV_CANTIDAD,DIC_CANTIDAD,
       ENE_COSTOS,FEB_COSTOS,MAR_COSTOS,ABR_COSTOS,MAY_COSTOS,JUN_COSTOS,JUL_COSTOS,AGO_COSTOS,SET_COSTOS,OCT_COSTOS,NOV_COSTOS,DIC_COSTOS,
       ENE_COSTOS+FEB_COSTOS+MAR_COSTOS+ABR_COSTOS+MAY_COSTOS+JUN_COSTOS+JUL_COSTOS+AGO_COSTOS+SET_COSTOS+OCT_COSTOS+NOV_COSTOS+DIC_COSTOS COSTO_TOTAL,
       ENE_CANTIDAD+FEB_CANTIDAD+MAR_CANTIDAD+ABR_CANTIDAD+MAY_CANTIDAD+JUN_CANTIDAD+JUL_CANTIDAD+AGO_CANTIDAD+SET_CANTIDAD+OCT_CANTIDAD+NOV_CANTIDAD+DIC_CANTIDAD CANTIDAD_TOTAL,
       DIVISION_COMERCIAL, AREA_COMERCIAL, SECCION_COMERCIAL, CATEGORIA_COMERCIAL, FAMILIA_COMERCIAL, SUBFAMILIA_COMERCIAL

FROM
(
SELECT
    CADENA,
    CENTRO,
    CADENA_2,
    NOMBRE,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    MES_NUMERO,
    COALESCE(SUM(CANTIDAD), 0) AS CANTIDAD,
    COALESCE(SUM(COSTOS) , 0) AS COSTOS,
    DIVISION_COMERCIAL,
    AREA_COMERCIAL,
    SECCION_COMERCIAL,
    CATEGORIA_COMERCIAL,
    FAMILIA_COMERCIAL,
    SUBFAMILIA_COMERCIAL
FROM
    (
    SELECT
        DECODE(o.des_formato, 'CD', 'CD', 'TIENDA') AS CADENA,
        o.CENTRO_SAP AS CENTRO,
        o.DES_FORMATO AS CADENA_2,
        o.ORG_NAME_FULL AS NOMBRE,
        pr.PRD_LVL_NUMBER AS CODIGO_PRODUCTO,
        pr.PRD_FULL_NAME AS DESCRIPCION_PRODUCTO,
        TO_NUMBER(TO_CHAR(vt.trans_date, 'MM')) AS MES_NUMERO,
        vt.TRANS_QTY_IN + vt.TRANS_QTY_OU AS CANTIDAD,
        vt.TRANS_COS_IN + vt.TRANS_COS_OU AS COSTOS,
        pr.DES_DIV AS DIVISION_COMERCIAL,
        pr.DES_AREA AS AREA_COMERCIAL,
        pr.DES_SEC AS SECCION_COMERCIAL,
        pr.DES_CAT AS CATEGORIA_COMERCIAL,
        pr.DES_FAM AS FAMILIA_COMERCIAL,
        pr.DES_SFAM AS SUBFAMILIA_COMERCIAL
    FROM
        einterface.kd_kardet_vt vt
    INNER JOIN
        edsr.ifhprdmst pr ON vt.TRANS_PRD_CHILD = pr.PRD_LVL_CHILD
    INNER JOIN
        einterface.ifhorgmst o ON o.org_lvl_child = vt.org_lvl_child
    WHERE
        vt.COD_TIP_OPR = '01' AND pr.cod_area IN ('A15', 'A02', 'A04')
    UNION ALL
    SELECT
        DECODE(o.des_formato,'CD','CD','TIENDA') CADENA,
        o.CENTRO_SAP CENTRO,
        o.DES_FORMATO CADENA_2,
        o.ORG_NAME_FULL NOMBRE,
        pr.PRD_LVL_NUMBER CODIGO_PRODUCTO,
        pr.PRD_FULL_NAME DESCRIPCION_PRODUCTO,
        TO_NUMBER(TO_CHAR(vt.trans_date, 'MM')) AS MES_NUMERO,
        vt.TRANS_QTY_IN + vt.TRANS_QTY_OU CANTIDAD,
        vt.TRANS_COS_IN + vt.TRANS_COS_OU  COSTOS,
        pr.DES_DIV DIVISION_COMERCIAL,
        pr.DES_AREA AREA_COMERCIAL,
        pr.DES_SEC SECCION_COMERCIAL,
        pr.DES_CAT CATEGORIA_COMERCIAL,
        pr.DES_FAM FAMILIA_COMERCIAL,
        pr.DES_SFAM SUBFAMILIA_COMERCIAL    
from 
    EINTERFACE.KD_KARDET_OTROS vt
INNER JOIN 
    edsr.ifhprdmst pr on vt.TRANS_PRD_CHILD = pr.PRD_LVL_CHILD
INNER JOIN 
    einterface.ifhorgmst o on o.org_lvl_child =vt.org_lvl_child
WHERE 
vt.COD_TIP_OPR='01' and  pr.cod_area in ('A15','A02','A04')
UNION ALL
SELECT
        decode(des_formato,'CD','CD','TIENDA') CADENA,
        o.CENTRO_SAP CENTRO,
        o.DES_FORMATO CADENA_2,
        o.ORG_NAME_FULL NOMBRE,
        pr.PRD_LVL_NUMBER CODIGO_PRODUCTO,
        pr.PRD_FULL_NAME DESCRIPCION_PRODUCTO,
        TO_NUMBER(TO_CHAR(TO_DATE(vt.FECHA_EMISION,'dd/mm/yyyy'), 'MM')) AS MES_NUMERO,
        vt.CANTIDAD_INGRESO + vt.CANTIDAD_RETIRO CANTIDAD,
        vt.COSTO_TOTAL_INGRESO + vt.COSTO_TOTAL_RETIRADO  COSTOS,
        pr.DES_DIV DIVISION_COMERCIAL,
        pr.DES_AREA AREA_COMERCIAL,
        pr.DES_SEC SECCION_COMERCIAL,
        pr.DES_CAT CATEGORIA_COMERCIAL,
        pr.DES_FAM FAMILIA_COMERCIAL,
        pr.DES_SFAM SUBFAMILIA_COMERCIAL    
from 
EINTERFACE.KD_KARDET_ARCHIVO_SAP_2018 vt
inner join 
edsr.ifhprdmst pr on TO_NUMBER(vt.COD_EXISTENCIA_CATALOGO) = pr.PRD_LVL_NUMBER
inner join 
einterface.ifhorgmst o on o.CENTRO_SAP =vt.WERKS_2
WHERE 
vt.TIPO_OPERACION='01' and pr.cod_area in ('A15','A02','A04'))
GROUP BY
    CADENA,
    CENTRO,
    CADENA_2,
    NOMBRE,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    MES_NUMERO,
    DIVISION_COMERCIAL,
    AREA_COMERCIAL,
    SECCION_COMERCIAL,
    CATEGORIA_COMERCIAL,
    FAMILIA_COMERCIAL,
    SUBFAMILIA_COMERCIAL
)   
PIVOT (
    SUM(CANTIDAD) AS CANTIDAD, SUM(COSTOS) AS COSTOS
    FOR MES_NUMERO IN (1 AS "ENE", 2 AS "FEB", 3 AS "MAR", 4 AS "ABR", 5 AS "MAY", 6 AS "JUN", 7 AS "JUL", 8 AS "AGO", 9 AS "SET", 10 AS "OCT", 11 AS "NOV", 12 AS "DIC")
)
ORDER BY
    CODIGO_PRODUCTO;
