SELECT CADENA, CENTRO, CADENA_2, NOMBRE, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, 
NVL(ENE_CANTIDAD,0)ENE_CANTIDAD_SUM, NVL(FEB_CANTIDAD,0)FEB_CANTIDAD_SUM, NVL(MAR_CANTIDAD,0)MAR_CANTIDAD_SUM, 
NVL(ABR_CANTIDAD,0)ABR_CANTIDAD_SUM, NVL(MAY_CANTIDAD,0)MAY_CANTIDAD_SUM, NVL(JUN_CANTIDAD,0)JUN_CANTIDAD_SUM,
NVL(JUL_CANTIDAD,0)JUL_CANTIDAD_SUM,NVL(AGO_CANTIDAD,0)AGO_CANTIDAD_SUM,NVL(SET_CANTIDAD,0)SET_CANTIDAD_SUM,
NVL(OCT_CANTIDAD,0)OCT_CANTIDAD_SUM, NVL(NOV_CANTIDAD,0)NOV_CANTIDA_SUM, NVL(DIC_CANTIDAD,0)DIC_CANTIDAD_SUM,

NVL(ENE_COSTOS,0)ENE_COSTOS_SUM, NVL(FEB_COSTOS,0)FEB_COSTOS_SUM,NVL(MAR_COSTOS,0)MAR_COSTOS_SUM,
NVL(ABR_COSTOS,0)ABR_COSTOS_SUM,NVL(MAY_COSTOS,0)MAY_COSTOS_SUM,NVL(JUN_COSTOS,0)JUN_COSTOS_SUM,
NVL(JUL_COSTOS,0)JUL_COSTOS_SUM,NVL(AGO_COSTOS,0)AGO_COSTOS_SUM, NVL(SET_CANTIDAD,0)SET_CANTIDAD_SUM, 
NVL(OCT_COSTOS,0)OCT_COSTOS_SUM,NVL(NOV_COSTOS,0)NOV_COSTOS_SUM,NVL(DIC_COSTOS,0)DIC_COSTOS_SUM,

(NVL(ENE_COSTOS,0)+ NVL(FEB_COSTOS,0)+NVL(MAR_COSTOS,0)+
NVL(ABR_COSTOS,0)+NVL(MAY_COSTOS,0)+NVL(JUN_COSTOS,0)+
NVL(JUL_COSTOS,0)+NVL(AGO_COSTOS,0)+ NVL(SET_CANTIDAD,0)+ 
NVL(OCT_COSTOS,0)+NVL(NOV_COSTOS,0)+NVL(DIC_COSTOS,0))COSTO_TOTAL,

(NVL(ENE_CANTIDAD,0)+ NVL(FEB_CANTIDAD,0)+NVL(MAR_CANTIDAD,0)+NVL(ABR_CANTIDAD,0)+ NVL(MAY_CANTIDAD,0)+ 
 NVL(JUN_CANTIDAD,0)+NVL(JUL_CANTIDAD,0)+NVL(AGO_CANTIDAD,0)+NVL(SET_CANTIDAD,0)+NVL(OCT_CANTIDAD,0)+ 
 NVL(NOV_CANTIDAD,0)+ NVL(DIC_CANTIDAD,0))CANTIDAD_TOTAL,
 DIVISION_COMERCIAL,
 AREA_COMERCIAL,
 SECCION_COMERCIAL,
 CATEGORIA_COMERCIAL,
 FAMILIA_COMERCIAL,
 SUBFAMILIA_COMERCIAL 
FROM
(
 select
            decode(o.des_formato,'CD','CD','TIENDA') CADENA,
            o.CENTRO_SAP CENTRO,
            o.DES_FORMATO CADENA_2,
            o.ORG_NAME_FULL NOMBRE,
            pr.PRD_LVL_NUMBER CODIGO_PRODUCTO,
            pr.PRD_FULL_NAME DESCRIPCION_PRODUCTO,
            EXTRACT(MONTH FROM vt.trans_date)MES,
           sum(vt.TRANS_QTY_IN + vt.TRANS_QTY_OU)CANTIDAD,
           sum(vt.TRANS_COS_IN + vt.TRANS_COS_OU)  COSTOS,
           pr.DES_DIV DIVISION_COMERCIAL,
           pr.DES_AREA AREA_COMERCIAL,
           pr.DES_SEC SECCION_COMERCIAL,
           pr.DES_CAT CATEGORIA_COMERCIAL,
           pr.DES_FAM FAMILIA_COMERCIAL,
           pr.DES_SFAM SUBFAMILIA_COMERCIAL  
    from einterface.kd_kardet_vt vt
    inner join edsr.ifhprdmst pr on vt.TRANS_PRD_CHILD = pr.PRD_LVL_CHILD
    inner join einterface.ifhorgmst o on o.org_lvl_child =vt.org_lvl_child
    WHERE vt.COD_TIP_OPR='01' and  pr.cod_area in ('A15','A02','A04')
    group by  o.CENTRO_SAP,o.DES_FORMATO,o.ORG_NAME_FULL,pr.PRD_LVL_NUMBER,pr.PRD_FULL_NAME,vt.COD_TIP_OPR,EXTRACT(MONTH FROM vt.trans_date),decode(o.des_formato,'CD','CD','TIENDA'),
    pr.DES_DIV,pr.DES_AREA,pr.DES_SEC,pr.DES_CAT,pr.DES_FAM,pr.DES_SFAM

union
select
        decode(o.des_formato,'CD','CD','TIENDA') CADENA,
        o.CENTRO_SAP CENTRO,
        o.DES_FORMATO CADENA_2,
        o.ORG_NAME_FULL NOMBRE,
        pr.PRD_LVL_NUMBER CODIGO_PRODUCTO,
        pr.PRD_FULL_NAME DESCRIPCION_PRODUCTO,
        EXTRACT(MONTH FROM vt.trans_date)MES,
       sum(vt.TRANS_QTY_IN + vt.TRANS_QTY_OU) CANTIDAD,
       sum(vt.TRANS_COS_IN + vt.TRANS_COS_OU)  COSTOS,
           pr.DES_DIV DIVISION_COMERCIAL,
           pr.DES_AREA AREA_COMERCIAL,
           pr.DES_SEC SECCION_COMERCIAL,
           pr.DES_CAT CATEGORIA_COMERCIAL,
           pr.DES_FAM FAMILIA_COMERCIAL,
           pr.DES_SFAM SUBFAMILIA_COMERCIAL    
from EINTERFACE.KD_KARDET_OTROS vt
inner join edsr.ifhprdmst pr on vt.TRANS_PRD_CHILD = pr.PRD_LVL_CHILD
inner join einterface.ifhorgmst o on o.org_lvl_child =vt.org_lvl_child
WHERE vt.COD_TIP_OPR='01' and  pr.cod_area in ('A15','A02','A04')
group by  o.CENTRO_SAP,o.DES_FORMATO,o.ORG_NAME_FULL,pr.PRD_LVL_NUMBER,pr.PRD_FULL_NAME,vt.COD_TIP_OPR,EXTRACT(MONTH FROM vt.trans_date),decode(o.des_formato,'CD','CD','TIENDA'),
    pr.DES_DIV,pr.DES_AREA,pr.DES_SEC,pr.DES_CAT,pr.DES_FAM,pr.DES_SFAM

UNION
select
        decode(des_formato,'CD','CD','TIENDA') CADENA,
        o.CENTRO_SAP CENTRO,
        o.DES_FORMATO CADENA_2,
        o.ORG_NAME_FULL NOMBRE,
        pr.PRD_LVL_NUMBER CODIGO_PRODUCTO,
        pr.PRD_FULL_NAME DESCRIPCION_PRODUCTO,
        EXTRACT(MONTH FROM to_date(vt.FECHA_EMISION,'dd/mm/yyyy'))MES,
        sum(vt.CANTIDAD_INGRESO + vt.CANTIDAD_RETIRO) CANTIDAD,
        sum(vt.COSTO_TOTAL_INGRESO + vt.COSTO_TOTAL_RETIRADO)  COSTOS,
           pr.DES_DIV DIVISION_COMERCIAL,
           pr.DES_AREA AREA_COMERCIAL,
           pr.DES_SEC SECCION_COMERCIAL,
           pr.DES_CAT CATEGORIA_COMERCIAL,
           pr.DES_FAM FAMILIA_COMERCIAL,
           pr.DES_SFAM SUBFAMILIA_COMERCIAL    
from EINTERFACE.KD_KARDET_ARCHIVO_SAP_2018 vt
inner join edsr.ifhprdmst pr on TO_NUMBER(vt.COD_EXISTENCIA_CATALOGO) = pr.PRD_LVL_NUMBER
inner join einterface.ifhorgmst o on o.CENTRO_SAP =vt.WERKS_2
WHERE vt.TIPO_OPERACION='01' and pr.cod_area in ('A15','A02','A04')
group by  o.CENTRO_SAP,o.DES_FORMATO,o.ORG_NAME_FULL,pr.PRD_LVL_NUMBER,pr.PRD_FULL_NAME,EXTRACT(MONTH FROM to_date(vt.FECHA_EMISION,'dd/mm/yyyy')),vt.TIPO_OPERACION,decode(o.des_formato,'CD','CD','TIENDA'),
pr.DES_DIV,pr.DES_AREA,pr.DES_SEC,pr.DES_CAT,pr.DES_FAM,pr.DES_SFAM

) 
PIVOT
    (
    SUM(CANTIDAD)CANTIDAD,SUM(COSTOS)COSTOS
    FOR MES
    IN (1 "ENE",2 "FEB",3 "MAR",4 "ABR",5 "MAY",6 "JUN",7 "JUL",8 "AGO",9 "SET", 10 "OCT",11 "NOV",12 "DIC")
    )
ORDER BY CODIGO_PRODUCTO